services:
  registry:
    image: registry:2.7
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Private Docker Registry"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
      - ./config.yml:/etc/docker/registry/config.yml:ro
    user: "1000:1000"

  registry-ui:
    image: soaraid/registry-ui:latest
    container_name: registry-ui
    restart: unless-stopped
    ports:
      - "8101:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      REGISTRY_URL: http://registry:5000
      REGISTRY_USERNAME: root
      REGISTRY_PASSWORD: 123123123
      REGISTRY_BEARER_TOKEN: ""

      APP_AUTH_USERNAME: operator
      APP_AUTH_PASSWORD: 123123123
      APP_SESSION_SECRET: replace-here-with-a-long-random-secret

      APP_BRAND_NAME: Soara
      APP_PRODUCT_NAME: Registry UI
